### ISSUE TITLE
Too many math alphabets

### ISSUE THREAD

**Issue by maxsnew** [wilbowma/mttex#39]
Since the switch to pacmpl, for our last paper, and a current draft I'm working on, @gasche and I have had to use a fork because we get the dreaded "too many math alphabets" error. https://github.com/gasche/mttex/commit/f8ff5f711ee5f32e906b2f51d205b95348db3d4c

**Comment by gasche** [comment]
(I suppose that I was a bit radical in the commit above because I battled with this error for a good hour before finding this solution, and was looking for rapid relief. It might be possible to disable less things. In general this strengthened my resolve in having someone split mttex in several independent libraries instead of bundling everything together.)

**Comment by wilbowma** [comment]
Closed by  428a93e
